### ISSUE TITLE
Mod release contains .git and .vscode folders

### ISSUE THREAD

**Issue by plague006** [mitsuyoshi-yamazaki/Camera-san#6]
It doesn't break anything with the mod, but thought you might want to know you're including your full git commit history in your mod. :)

**Comment by mitsuyoshi-yamazaki** [comment]
@plague006 thanks!

**Comment by mitsuyoshi-yamazaki** [comment]
Fixed in v1.1.1
https://mods.factorio.com/mod/Camera-san
